### ISSUE TITLE
Setup errors

### ISSUE THREAD

**Issue by iRacer96** [kyleflan/tempiture#5]
Good evening again, I have narrowed my list of errors down quite substantially, but there are still some that I cannot figure out. Can someone look at this and possibly point me in the right direction? FWIW I am running:  
"PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

`pi@raspberrypi:~ $ cd tempiture
pi@raspberrypi:~/tempiture $ chmod +x ./setup.sh
pi@raspberrypi:~/tempiture $ sudo ./setup.sh

## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:3 https://deb.nodesource.com/node_6.x stretch InRelease
Hit:4 https://packagecloud.io/Hypriot/Schatzkiste/debian jessie InRelease
Reading package lists... Done

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 6.x LTS Boron repo...

+ echo 'deb https://deb.nodesource.com/node_6.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_6.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 https://deb.nodesource.com/node_6.x stretch InRelease
Hit:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:3 https://packagecloud.io/Hypriot/Schatzkiste/debian jessie InRelease
Reading package lists... Done

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (8.11.1~dfsg-2~bpo9+1).
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
jq is already the newest version (1.5+dfsg-1.3).
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2+rpt2).
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
Collecting docker-compose
  Using cached https://files.pythonhosted.org/packages/dd/e6/1521d1dfd9c0da1d1863b18e592d91c3df222e55f258b9876fa1e59bc4b5/docker_compose-1.24.1-py2.py3-none-any.whl
Collecting docker[ssh]<4.0,>=3.7.0 (from docker-compose)
  Using cached https://files.pythonhosted.org/packages/09/da/7cc7ecdcd01145e9924a8ccbe9c1baf3a362fc75d4cb150676eb5231ea60/docker-3.7.3-py2.py3-none-any.whl
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-compose)
Requirement already satisfied: websocket-client<1.0,>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-compose)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from docker-compose)
Collecting PyYAML<4.3,>=3.10 (from docker-compose)
Collecting dockerpty<0.5,>=0.4.1 (from docker-compose)
Collecting texttable<0.10,>=0.9.0 (from docker-compose)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
OK
deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://deb.nodesource.com/node_6.x stretch InRelease
Hit:4 https://packagecloud.io/Hypriot/Schatzkiste/debian jessie InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker-hypriot is already the newest version (1.11.1-1).
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
./setup.sh: line 33: npm: command not found
sudo: npm: command not found
curl: (6) Could not resolve host: tempiture.local
curl: (6) Could not resolve host: tempiture.local
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: tempiture.local
curl: (6) Could not resolve host: tempiture.local
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sudo: pm2: command not found
sudo: pm2: command not found
env: ‘/usr/lib/node_modules/pm2/bin/pm2’: No such file or directory
********************************************************************************
********************************************************************************

The setup has completed. You should change the admin password for your Grafana 
instance by logging in to http://localhost:3000/login and then choosing Menu -> 
Admin -> Global Users -> admin -> edit.

********************************************************************************
********************************************************************************
pi@raspberrypi:~/tempiture $ 
`

**Comment by kyleflan** [comment]
If you run `pip install docker-compose` outside of the setup script, are the errors the same? Looks like the issue might be getting texttable. Can you try `pip install texttable <0.10,>=0.9.0` and see how that works?

**Comment by iRacer96** [comment]
I tried `pip install docker-compose`, received the same errors I believe.  [Pastebin](https://pastebin.com/jynCt2b3)

**Comment by iRacer96** [comment]
ok, I first tried `pip install texttable <0.10,>=0.9.0`, that didn't work. I then tried that same code without <0.10,>=0.9.0 and that seemed to get me further along. Now I still have a bunch of red text starting at "Exception" and ending at "Type error".... here's the file... [pastebin](https://pastebin.com/y9A4zqai).
